services:
  winvnc:
    image: dockurr/windows:latest
    container_name: winvnc
    environment:
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      KVM: "N"
      VNC_PORT: "5900"
      VNC_PASSWORD: "1234"
      VERSION: "2012"
      DISK_FILE: "/data/win.img"
    ports:
      - "5900:5900"
    volumes:
      - ./data:/data
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
