services:
  winvnc:
    image: dockurr/windows:latest   # hoặc image custom mày đã build
    container_name: winvnc
    environment:
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DISK_SIZE: "10G"
      KVM: "N"
      VNC_PORT: "5900"
      VNC_PASSWORD: "1234"
      DISK_FILE: "/data/win.img"   # dùng disk.img sẵn có
    ports:
      - "5900:5900"
    volumes:
      - ./data:/data   # ./data chứa win.img
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
