version: "3.8"

services:
  winvnc:
    image: dockurr/windows:latest
    container_name: winvnc
    environment:
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DISK_SIZE: "10G"
      KVM: "N"
      VNC_PORT: "5900"
      VNC_PASSWORD: "1234"
      VERSION: "2022"   # <-- chá»n Windows Server 2022
    ports:
      - "5900:5900"
    volumes:
      - ./data:/data
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
