services:
  winvnc:
    image: dockurr/windows:latest
    container_name: winvnc
    environment:
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      KVM: "N"
      VNC_PORT: "5900"
      VNC_PASSWORD: "1234"
    ports:
      - "5900:5900"
    volumes:
      - winvnc-data:/data
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

volumes:
  winvnc-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/winvnc-data   # chá»©a file disk 10GB
